/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.8
 * Generated at: 2023-06-28 06:28:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.sql.*;
import java.sql.*;

public final class adminPanel_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/STFeedBack.jsp", Long.valueOf(1687933552070L));
    _jspx_dependants.put("/AllStudent.jsp", Long.valueOf(1687933734365L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC\" crossorigin=\"anonymous\">\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM\" crossorigin=\"anonymous\"></script>\n");
      out.write("    <!--Jquery-->\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js\"></script>\n");
      out.write("\n");
      out.write("     \n");
      out.write("        <style>\n");
      out.write("            .FEED{\n");
      out.write("               background-color: darkgray;\n");
      out.write("            }\n");
      out.write("            .spn{\n");
      out.write("                color: #6A67CE;\n");
      out.write("                font-family: sans-serif;\n");
      out.write("                font-size:30px;\n");
      out.write("                margin: 1px 10px;\n");
      out.write("            }\n");
      out.write("            #lagout{\n");
      out.write("                   background-color: #6A67CE;\n");
      out.write("               box-shadow: .2px 1px 2px black;\n");
      out.write("               border: none;\n");
      out.write("                font-size: 10px;\n");
      out.write("                font-weight: bold; \n");
      out.write("            }\n");
      out.write("            .btns a{\n");
      out.write("                background-color: #6A67CE;\n");
      out.write("               box-shadow: .2px 1px 2px black;\n");
      out.write("               border: none;\n");
      out.write("                font-size: 10px;\n");
      out.write("                font-weight: bold; \n");
      out.write("            }\n");
      out.write("            \n");
      out.write("       \n");
      out.write("</style>  \n");
      out.write("<body>\n");

try{
String Username=session.getAttribute("sUserName").toString();

      out.write("\n");
      out.write("<div class=\"container-fluid FEED\">\n");
      out.write("  \n");
      out.write("    <div class=\"row \">\n");
      out.write("           <div class=\"col-md-1 p-3\">\n");
      out.write("               <a type=\"submit\" class=\"btn btn-outline-light \" id=\"lagout\" href=\"logoutpage.jsp\">Logout</a>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-md-12 \">\n");
      out.write("            <div class=\" container-fluid d-flex justify-content-center\">\n");
      out.write("            <h1 class=\"\" style=\"font-family: sans-serif;\">FACULTY PANEL : </h1>\n");
      out.write("            <span class=\"spn \">");
out.println(Username);
      out.write(" </span>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <!--BTN COONTAIN-->\n");
      out.write("        <div class=\"col btns\">\n");
      out.write("            <div class=\"row m-5\">\n");
      out.write("                \n");
      out.write("                <div class=\"col\">\n");
      out.write("                    <a type=\"submit\" class=\"btn btn-outline-light \" href=\"#\" id=\"ShowFeedBack\">STUDENT FEED BACK</a>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col\">\n");
      out.write("                    <a type=\"submit\" class=\"btn btn-outline-light \" href=\"#\" id=\"Show2\">ALL STUDENT</a>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");

    }
    catch(Exception ex)
    {
    session.setAttribute("msg","Pleas Login Frist");
    response.sendRedirect("loginProces.jsp");
    
    }

      out.write("\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("<!--Feed Back Content-->\n");
      out.write("<div class=\"Container\">\n");
      out.write("     <div class=\"h1 text-center mt-3 text-light bg-danger\">ALL STUDENT DATA</div>\n");
      out.write("    <div class=\"\" id=\"FEEDBACK\">\n");
      out.write("    ");
      out.write("\n");
      out.write("   <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC\" crossorigin=\"anonymous\">\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM\" crossorigin=\"anonymous\"></script>\n");
      out.write("\n");
      out.write("    <style>\n");
      out.write("    .cont{\n");
      out.write("         height: 600px;\n");
      out.write("         overflow-y: scroll; \n");
      out.write("    }\n");
      out.write("    .srlc{\n");
      out.write("         position:sticky;\n");
      out.write("                    top:0; \n");
      out.write("    }\n");
      out.write("</style>\n");
      out.write("    \n");
      out.write("    <div class=\"container cont\"> \n");
      out.write("        <div class=\"row srlc \">\n");
      out.write("\n");

    Class.forName("com.mysql.jdbc.Driver");
    Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/sessionproject","root","root");
//    out.print("Connect");
try{
    Statement st=con.createStatement();
    ResultSet rs=st.executeQuery("select * from contact");
    while(rs.next()){
//        out.print(rs.getString("message"));

      out.write("\n");
      out.write("\n");
      out.write("    <div class=\"col-md-4 \">\n");
      out.write("    <div class=\"container text-light\" style=\"border: 1px solid gray; background-image: url('pics/girl.jpg'); background-size: cover;\" >\n");
      out.write("      <div class=\"row\">\n");
      out.write("        <div class=\"col-md-12\" style=\"background: linear-gradient(rgba(0, 0, 0, .5),rgba(0, 0, 0, .5));\">\n");
      out.write("          <div class=\"h4 text-center p-2\" style=\"border-radius: 10px;\">Name :");
      out.print(rs.getString("name"));
      out.write("</div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"row \">\n");
      out.write("        <div class=\"col-md-12 text-center p-4\">\n");
      out.write("          <div class=\"row\">\n");
      out.write("            <div class=\"col-md-6 \">\n");
      out.write("              <div class=\"h6 \">E-mail ");
      out.print(rs.getString("email"));
      out.write("</div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-md-5 \">\n");
      out.write("                <div class=\"h6 ps-5\">Contact ");
      out.print(rs.getString("contact"));
      out.write("</div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-md-12 p-3\">\n");
      out.write("          <div class=\"h4 \">ID :");
      out.print(rs.getString("id"));
      out.write("</div>          \n");
      out.write("        </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-md-12 p-2 \">\n");
      out.write("            <div class=\"h6\">Message :<span class=\"text-warning\"> ");
      out.print(rs.getString("message"));
      out.write("</span></div>          \n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-md-12 text-center\" style=\"background: linear-gradient(rgba(0, 0, 0, .5),rgba(0, 0, 0, .5));\">\n");
      out.write("          <a href=\"UpadateFeedBack.jsp?id=");
      out.print(rs.getString("id"));
      out.write("\" class=\"btn btn-outline-success m-2 \">UP DATE</a>\n");
      out.write("          <a href=\"DeletFeedBack.jsp?id=");
      out.print(rs.getString("id"));
      out.write("\" class=\"btn btn-outline-danger m-2\">DELET</a>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("    </div>\n");

    }
    }
    catch (Exception e)
    {
    out.println(e);
    }



      out.write("\n");
      out.write("        </div>\n");
      out.write("    </div>");
      out.write("\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<!--All Student-->\n");
      out.write("\n");
      out.write("    <div class=\"Container\">\n");
      out.write("        <div class=\"h1 text-center mt-3 text-light bg-danger\">ALL STUDENT DATA</div>\n");
      out.write("    <div class=\"\" id=\"Display2\">\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("		.bgim{\r\n");
      out.write("			background: linear-gradient(rgba(0, 0, 0, 0.5),rgba(0, 0, 0, 0.5)),url('img/ControlPanelBg.jpg');\r\n");
      out.write("			background-size: cover;\r\n");
      out.write("			color: white;\r\n");
      out.write("		}\r\n");
      out.write("		th{\r\n");
      out.write("			color: orange;\r\n");
      out.write("			border: 1px solid white;\r\n");
      out.write("		}\r\n");
      out.write("                		td{\r\n");
      out.write("			border: 1px solid white;	\r\n");
      out.write("		}\r\n");
      out.write("                a{\r\n");
      out.write("                    color:white;\r\n");
      out.write("                    text-decoration: none;\r\n");
      out.write("                }\r\n");
      out.write("           \r\n");
      out.write("                .tabel{\r\n");
      out.write("                    height: 500px;\r\n");
      out.write("                    overflow-y: scroll;\r\n");
      out.write("                    \r\n");
      out.write("                }\r\n");
      out.write("                .tabledata th{\r\n");
      out.write("                    position:sticky;\r\n");
      out.write("                    top:0;\r\n");
      out.write("                   \r\n");
      out.write("                }\r\n");
      out.write("                \r\n");
      out.write("	</style> \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");

        try{
    
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<div class=\"tabel \" >\r\n");
      out.write("			<table class=\"table table-dark table-striped \">\r\n");
      out.write("                            <tr class=\" tabledata\">\r\n");
      out.write("                                <th>S,no</th>\r\n");
      out.write("					<th>Name</th>\r\n");
      out.write("					<th>Last Name</th>\r\n");
      out.write("					<th>Contact</th>\r\n");
      out.write("					<th>Password</th>\r\n");
      out.write("                                        <th>Email</th>\r\n");
      out.write("                                        <th>Update</th>\r\n");
      out.write("                                        <th>Delete</th>\r\n");
      out.write("				</tr>  \r\n");
      out.write("        ");
     
        Statement st=con.createStatement();
        String sql ="select * from loginpage";
         ResultSet rs = st.executeQuery(sql);
        while(rs.next())
        {
        
      out.write("\r\n");
      out.write("        <tr class=\"td\">\r\n");
      out.write("       <td>");
      out.print(rs.getString("id"));
      out.write("</td>\r\n");
      out.write("        <td>");
      out.print(rs.getString("name"));
      out.write("</td>\r\n");
      out.write("        <td>");
      out.print(rs.getString("lname"));
      out.write("</td>\r\n");
      out.write("        <td>");
      out.print(rs.getString("contact"));
      out.write("</td>\r\n");
      out.write("        <td>");
      out.print(rs.getString("password"));
      out.write("</td>\r\n");
      out.write("        <td>");
      out.print(rs.getString("email"));
      out.write("</td>\r\n");
      out.write("        <td class=\"upd\"><a href=\"AllStudentUpadatePage.jsp?id=");
      out.print(rs.getString("id"));
      out.write("\" class=\"btn btn-outline-success\">Update</a></td>\r\n");
      out.write("        <td class=\"delt\"><a href=\"StudentDataDeletd.jsp?id=");
      out.print(rs.getString("id"));
      out.write("\" class=\"btn btn-outline-danger\">Delete</a></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("	\r\n");

    }
con.close();
}
catch (Exception e)
{
out.println(e);
}

      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("</div>");
      out.write("\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("    \n");
      out.write("<!--Script-->\n");
      out.write("<script> \n");
      out.write("    $(document).ready(function(){\n");
      out.write("       $(\"#ShowFeedBack\").click(function(){ \n");
      out.write("          $(\"#FEEDBACK\").fadeToggle() \n");
      out.write("       });\n");
      out.write("       \n");
      out.write("        $(\"#Show2\").click(function(){ \n");
      out.write("          $(\"#Display2\").fadeToggle() \n");
      out.write("       });\n");
      out.write("       \n");
      out.write("     \n");
      out.write("    }); \n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
