/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.8
 * Generated at: 2023-06-28 06:19:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <!-- font awesome -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\" integrity=\"sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\n");
      out.write("\n");
      out.write("    <!-- boostrap file link -->\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC\" crossorigin=\"anonymous\">\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM\" crossorigin=\"anonymous\"></script>\n");
      out.write("   <style>\n");
      out.write("      .NAVCOL a{\n");
      out.write("        color: #6A67CE;\n");
      out.write("        \n");
      out.write("      }\n");
      out.write("      #NAVCOL {\n");
      out.write("        color:white;\n");
      out.write("        padding-right: 25px;\n");
      out.write("      \n");
      out.write("      }\n");
      out.write("      .maiCont{\n");
      out.write("         position:sticky;\n");
      out.write("        top:0;   \n");
      out.write("      }\n");
      out.write("      #NAVCOL:hover{\n");
      out.write("        color: #6A67CE;\n");
      out.write("      }\n");
      out.write("      /* about us */\n");
      out.write("      .ABT i{\n");
      out.write("        font-size:4rem;\n");
      out.write("        border-radius: 50%;\n");
      out.write("        padding: 25px;\n");
      out.write("        background-color:azure;\n");
      out.write("      }\n");
      out.write("      .ABT i:hover{\n");
      out.write("        color: white;\n");
      out.write("        background-color: #6A67CE;\n");
      out.write("        transition: 0.6s;\n");
      out.write("\n");
      out.write("\n");
      out.write("      }\n");
      out.write("      #abutbtn{\n");
      out.write("        color: black;\n");
      out.write("      }\n");
      out.write("      #abutbtn:hover{\n");
      out.write("        background-color: #6A67CE;\n");
      out.write("        color: white;\n");
      out.write("      }\n");
      out.write("      /* WOS */\n");
      out.write("      .WOS img:hover{\n");
      out.write("        transform: rotate(360deg);\n");
      out.write("        transition: 0.3s;\n");
      out.write("      }\n");
      out.write("      /* SERVICES */\n");
      out.write("      .SERVICES{\n");
      out.write("        background:linear-gradient(rgba(0, 0, 0, .7),rgba(0, 0, 0, .7)),url(pics/a45400359e30246c12176310ee0bb9cb.jpg);\n");
      out.write("        background-size:  cover;\n");
      out.write("      }\n");
      out.write("      .SERVICES i{\n");
      out.write("        font-size: 3rem;\n");
      out.write("        color: white;\n");
      out.write("        padding: 20px;\n");
      out.write("      }\n");
      out.write("      /* Footer */\n");
      out.write("      .Footer {\n");
      out.write("        color: white;\n");
      out.write("        /*background-color: black;*/\n");
      out.write("        background-color:black;\n");
      out.write("      }\n");
      out.write("      .Footer a{\n");
      out.write("        color: white;\n");
      out.write("        font-size: 15px;\n");
      out.write("      }\n");
      out.write("    \n");
      out.write("      .Footer a:hover{\n");
      out.write("        color: #6A67CE;\n");
      out.write("      }\n");
      out.write("      .Footer .h3{\n");
      out.write("          color: #6A67CE;\n");
      out.write("      }\n");
      out.write("      /* Contact */\n");
      out.write("      .Contact{\n");
      out.write("        background: linear-gradient(rgba(0, 0, 0, .2),rgba(0, 0, 0, .2)),url(pics/a-note-just-to-say-you-are-enough.jpg);\n");
      out.write("        background-size: cover;\n");
      out.write("        \n");
      out.write("      }\n");
      out.write("      .Contact input{\n");
      out.write("        box-shadow: .2px .2px 5px black;\n");
      out.write("        background: none;\n");
      out.write("      }\n");
      out.write("      .Contact label{\n");
      out.write("        color: white;\n");
      out.write("      }\n");
      out.write("      \n");
      out.write("    </style>\n");
      out.write("    <title>Document</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <!-- navbar -->\n");
      out.write("    <div class=\"maiCont\">\n");
      out.write("    <div class=\"container-fluide bg-dark NAVCOL ps-3 pe-3 maiCont\" id=\"home\" style=\"font-family: sans-serif;\">\n");
      out.write("        <div class=\"container-fluide d-flex justify-content-end\">\n");
      out.write("                  <a class=\"nav-link active dropdown-toggle\" href=\"#\" id=\"navbarDropdown\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">Login</a>\n");
      out.write("                  <ul class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\n");
      out.write("                    <li><a class=\"dropdown-item\" href=\"StudentLoginPage.jsp\">Studen</a></li>\n");
      out.write("                    <li><a class=\"dropdown-item\" href=\"TeacherLoginForm.jsp\">Teacher</a></li>\n");
      out.write("                  </ul>\n");
      out.write("                   <a class=\"nav-link active dropdown-toggle\" href=\"#\" id=\"navbarDropdown\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">REGISTER</a>\n");
      out.write("                  <ul class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\n");
      out.write("                    <li><a class=\"dropdown-item\" href=\"RigisterPage.jsp\">Studen</a></li>\n");
      out.write("                    <li><a class=\"dropdown-item\" href=\"TeacherRegForm.jsp\">Teacher</a></li>\n");
      out.write("                  </ul>\n");
      out.write("            </div>\n");
      out.write("        <nav class=\"navbar navbar-expand-lg NAVCOL navbar-dark pb-3 \">\n");
      out.write("            <div class=\"container-fluid\">\n");
      out.write("              <button class=\"navbar-toggler \" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
      out.write("                <span class=\"navbar-toggler-icon \"></span>\n");
      out.write("              </button>\n");
      out.write("              <div class=\"collapse ps-5 nvba navbar-collapse\" id=\"navbarSupportedContent\">\n");
      out.write("                <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\n");
      out.write("                  <li class=\"nav-item\">\n");
      out.write("                    <a class=\"nav-link active\" id=\"NAVCOL\" aria-current=\"page\" href=\"#home\">HOME</a>\n");
      out.write("                  </li>\n");
      out.write("                  <li class=\"nav-item\">\n");
      out.write("                    <a class=\"nav-link active\" id=\"NAVCOL\" aria-current=\"page\" href=\"#about\">ABOUT US</a>\n");
      out.write("                  </li>\n");
      out.write("                  <li class=\"nav-item\">\n");
      out.write("                    <a class=\"nav-link active\" id=\"NAVCOL\" aria-current=\"page\" href=\"#service\">SERVICES</a>\n");
      out.write("                  </li>\n");
      out.write("<!--                  <li class=\"nav-item\">\n");
      out.write("                    <a class=\"nav-link active\" id=\"NAVCOL\" aria-current=\"page\" href=\"#\">FEED BACK</a>\n");
      out.write("                  </li>-->\n");
      out.write("                  <li class=\"nav-item\">\n");
      out.write("                    <a class=\"nav-link active\" id=\"NAVCOL\" aria-current=\"page\" href=\"#events\">EVENTS</a>\n");
      out.write("                  </li>\n");
      out.write("                  <li class=\"nav-item\">\n");
      out.write("                    <a class=\"nav-link active\" id=\"NAVCOL\" aria-current=\"page\" href=\"#contact\">CONTACT US</a>\n");
      out.write("                  </li>\n");
      out.write("                </ul>\n");
      out.write("                <form class=\"d-flex\">\n");
      out.write("                  <input class=\"form-control me-2\" type=\"search\" placeholder=\"Search\" aria-label=\"Search\">\n");
      out.write("                  <button class=\"btn text-light\" style=\"background-color: #6A67CE;\" type=\"submit\"><i class=\"fa-solid fa-magnifying-glass\"></i></button>\n");
      out.write("                </form>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </nav> \n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <!-- first contain  -->\n");
      out.write("    <div class=\"container-fluid p-5\"  style=\"background-image:url(pics/girl.jpg);background-size: cover;\">\n");
      out.write("      <div class=\"row p-5 \">\n");
      out.write("        <div class=\"col-md-12 p-5 text-center \" style=\"background: linear-gradient(rgba(0, 0, 0, .3),rgba(0, 0, 0, .3)); font-family: sans-serif;\">\n");
      out.write("          <div id=\"carouselExampleFade \" class=\"carousel slide carousel-fade text-light text-center \" data-bs-ride=\"carousel\">\n");
      out.write("          <div class=\"carousel-inner\" >\n");
      out.write("            <div class=\"carousel-item active\">\n");
      out.write("              <div class=\"h4 d-block \" >WISDOM BEGINS WITH WONDER.</div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"carousel-item\">\n");
      out.write("              <div class=\"h4 d-block \" >LEARNING NEVER EXHAUSTS THE MIND</div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"carousel-item\">\n");
      out.write("               <div class=\"h4 d-block\" >EDUCATION IS A VACCINE FOR VIOLENCE.</div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("          <button class=\"carousel-control-prev\" type=\"button\" data-bs-target=\"#carouselExampleFade\" data-bs-slide=\"prev\">\n");
      out.write("            <span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\n");
      out.write("            <span class=\"visually-hidden\">Previous</span>\n");
      out.write("          </button>\n");
      out.write("          <button class=\"carousel-control-next\" type=\"button\" data-bs-target=\"#carouselExampleFade\" data-bs-slide=\"next\">\n");
      out.write("            <span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\n");
      out.write("            <span class=\"visually-hidden\">Next</span>\n");
      out.write("          </button>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"h1 text-light\" style=\"font-weight: bold;\"><span style=\"color: #6A67CE;\">EDU</span> CATIONAL</div>\n");
      out.write("        <div class=\"h3 p-2  \" style=\"background-color: #6A67CE; color: white;\">WISDOM BEGINS WITH WONDER.</div>\n");
      out.write("        <br>\n");
      out.write("        <br>\n");
      out.write("      </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- About us -->\n");
      out.write("    <div class=\"container-fluid ABT text-center\" id=\"about\">\n");
      out.write("      <div class=\"container p-5\">\n");
      out.write("        <div class=\"h1\">ABOUT US</div>\n");
      out.write("          <div class=\"h4 \" style=\"font-family:'Covered By Your Grace', cursive;\">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod ut enim ad tempor incididunt ut labore et dolore magna aliqua.\n");
      out.write("          </div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"row m-5\">\n");
      out.write("        <div class=\"col-md-4\">\n");
      out.write("          <i class=\"fa-solid fa-graduation-cap\"></i>\n");
      out.write("          <div class=\"h3\">Awesome Education</div>\n");
      out.write("          <div class=\"h6\">\n");
      out.write("            Sed ut perspiciis iste natus error sit voluptatem accusantium doloremque laudantium elerisque ipsum vehicula pharetra.\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-md-4\">\n");
      out.write("          <i class=\"fa-sharp fa-solid fa-house\"></i>\n");
      out.write("          <div class=\"h3\">Awesome classes</div>\n");
      out.write("          <div class=\"h6\">\n");
      out.write("            Sed ut perspiciis iste natus error sit voluptatem accusantium doloremque laudantium elerisque ipsum vehicula pharetra.\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-md-4\">\n");
      out.write("          <i class=\"fa-solid fa-signature\"></i>\n");
      out.write("          <div class=\"h3\">Awesome Teachings</div>\n");
      out.write("          <div class=\"h6\">\n");
      out.write("            Sed ut perspiciis iste natus error sit voluptatem accusantium doloremque laudantium elerisque ipsum vehicula pharetra.\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col p-5 \">\n");
      out.write("          <a href=\"#\" class=\" p-3\" style=\"text-decoration: none; color: white; background-color: #6A67CE;\">CONTACT WITH US</a>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col p-5\">\n");
      out.write("          <a href=\"#\" class=\" p-3  \" id=\"abutbtn\" style=\"text-decoration: none;  border: 1px solid rgb(194, 197, 198);\">ADMISSION NOW</a>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Education -->\n");
      out.write("\n");
      out.write("    <div class=\"container-fluid\" id=\"ed\">\n");
      out.write("      <div class=\"row\">\n");
      out.write("        <div class=\"col-md-6\" style=\"background-image: url('pics/ab.jpeg');\">\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-md-6 p-5 text-light\" style=\"background-color: #6A67CE; \">\n");
      out.write("          <div class=\"h3\" style=\"font-family: sans-serif;\">EDUCATIONAL</div>\n");
      out.write("          <div class=\"h6\" style=\"font-family: cursive;\">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua Ut enim ad minim veniam Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</div>\n");
      out.write("          <div class=\"h3\" style=\"font-family: sans-serif;\">EDUCATIONAL</div>\n");
      out.write("          <div class=\"h6\" style=\"font-family: cursive;\">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua Ut enim ad minim veniam Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("\n");
      out.write("    <!-- why our school -->\n");
      out.write("\n");
      out.write("    <div class=\"container-fluide text-center mt-3 WOS\" id=\"service\" style=\"background-color:#44446e;\">\n");
      out.write("      <div class=\"h4 pt-5 text-light\">Our Schools & Centers</div>\n");
      out.write("      <div class=\"h5 \">All posses exceptional breadth and depth of excellence</div>\n");
      out.write("      <div class=\"row p-5 WOS\">\n");
      out.write("          <div class=\"col-md-3\">\n");
      out.write("              <img src=\"pics/icon1.png\" alt=\"\">\n");
      out.write("              <div class=\"h6  text-light\">School of Engineering & Technology</div>\n");
      out.write("              <div class=\"p\">\n");
      out.write("                  The School of Engineering & Technology was established in the year 2000 with a vision to develop technical professionals and leaders to create a significant hub for training technocrats in a national and international perspective.\n");
      out.write("              </div>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"col-md-3\">\n");
      out.write("              <img src=\"pics/icon2.png\" alt=\"\">\n");
      out.write("              <div class=\"h6 text-light\">International School of Business Management (ISBM)</div>\n");
      out.write("              <div class=\"p\">\n");
      out.write("                  We taught to students to transform them into potential leaders, future managers and innovative entrepreneurs. ISBM has been in operation for the 12 years and has set new benchmarks of excellence every year.\n");
      out.write("              </div>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"col-md-3\">\n");
      out.write("              <img src=\"pics/icon3.png\" alt=\"\">\n");
      out.write("              <div class=\"h6  text-light\">School of Applied Sciences</div>\n");
      out.write("              <div class=\"p\">\n");
      out.write("                  The School of Applied Sciences was established in the year 2003 with a vision to create a mark at global and national level through academia, research and technology-based training and innovation.\n");
      out.write("\n");
      out.write("              </div>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"col-md-3\">\n");
      out.write("              <img src=\"pics/icon4.png\" alt=\"\">\n");
      out.write("              <div class=\"h6  text-light\">School of Pharmacy</div>\n");
      out.write("              <div class=\"p\">\n");
      out.write("                  Gyan Vihar School of Pharmacy was established in the year 2003. The school offers undergraduate programs in the field of Pharmacy.\n");
      out.write("              </div>\n");
      out.write("          </div>\n");
      out.write("   \n");
      out.write("      <div class=\"col-md-3\">\n");
      out.write("          <img src=\"pics/icon5.png\" alt=\"\">\n");
      out.write("          <div class=\"h6  text-light\">School of Hotel Management</div>\n");
      out.write("          <div class=\"p\">\n");
      out.write("              Gyan Vihar School of Hotel Management is running since 2004. Renowned faculty from the leading hotels of the country provide innovative training to the upcoming hoteliers\n");
      out.write("          </div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"col-md-3\">\n");
      out.write("          <img src=\"pics/icon6.png\" alt=\"\">\n");
      out.write("          <div class=\"h6  text-light\">School of Agriculture</div>\n");
      out.write("          <div class=\"p\">\n");
      out.write("              School of Agriculture at SGVU completely changes the research and significant service by providing the skills necessary to develop farms to support the growing population and economy of the country.\n");
      out.write("          </div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"col-md-3\">\n");
      out.write("          <img src=\"pics/icon7.png\" alt=\"\">\n");
      out.write("          <div class=\"h6  text-light\">School of Health Care</div>\n");
      out.write("          <div class=\"p\">\n");
      out.write("              ?Health is a state of complete mental, social and physical well-being, not merely the absence of disease or infirmity.? Gyan Vihar School of Health Care fabricating future health care professionals reinforcing the medical team of the nation.\n");
      out.write("          </div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"col-md-3\">\n");
      out.write("          <img src=\"pics/icon8.png\" alt=\"\">\n");
      out.write("          <div class=\"h6  text-light\">School of Interdisciplinary & Liberal Studies</div>\n");
      out.write("          <div class=\"p\">\n");
      out.write("              This programs have been specifically tailored to allow students to fashion a course of study that blends their interests, talents, and experience.\n");
      out.write("          </div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"col-md-3\">\n");
      out.write("          <img src=\"pics/icon9.png\" alt=\"\">\n");
      out.write("          <div class=\"h6  text-light\">School of Law</div>\n");
      out.write("          <div class=\"p\">\n");
      out.write("              Suresh Gyan Vihar University has established a School of Law having BBA LL.B. (Hons.) Program and Ph. D Program. It is most beneficial for the students who have a strong interest in legal stream.\n");
      out.write("          </div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"col-md-3\">\n");
      out.write("          <img src=\"pics/icon10.png\" alt=\"\">\n");
      out.write("          <div class=\"h6  text-light\">School of Interdisciplinary & Liberal Studies</div>\n");
      out.write("          <div class=\"p\">\n");
      out.write("              This programs have been specifically tailored to allow students to fashion a course of study that blends their interests, talents, and experience.\n");
      out.write("          </div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"col-md-3\">\n");
      out.write("          <img src=\"pics/icon11.png\" alt=\"\">\n");
      out.write("          <div class=\"h6  text-light\">Centre for Climate Change and Water Research (C3WR)</div>\n");
      out.write("          <div class=\"p\">\n");
      out.write("              SGVU has made it into the league of a few selected institutes across the country Industrial teaching by a leading industry is a realistic augmentation for the students.\n");
      out.write("          </div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"col-md-3\">\n");
      out.write("          <img src=\"pics/icon12.png\" alt=\"\">\n");
      out.write("          <div class=\"h6  text-light\">Learning Centre of Excellence with Google</div>\n");
      out.write("          <div class=\"p\">\n");
      out.write("             Building pioneers of smart energy for a better tomorrow\n");
      out.write("          </div>\n");
      out.write("      </div>\n");
      out.write("  </div>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("    <!-- EVENTS -->\n");
      out.write("    <div class=\"container \" id=\"events\">\n");
      out.write("      <div class=\"h1 pt-5 text-center\">EVENTS</div>\n");
      out.write("      <div class=\"row p-5\">\n");
      out.write("        <div class=\"col-md-4\">\n");
      out.write("          <div class=\"card\" style=\"width: 18rem;\">\n");
      out.write("            <img src=\"pics/e2.jpeg\" class=\"card-img-top\" alt=\"...\">\n");
      out.write("            <div class=\"card-body\">\n");
      out.write("              <h5 class=\"card-title\" style=\"color: #6A67CE;\">EDUCATIONAL</h5>\n");
      out.write("              <p class=\"card-text\">By an admin, Oct-2016</p>\n");
      out.write("              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>\n");
      out.write("            </div>\n");
      out.write("        \n");
      out.write("            <div class=\"card-body\" style=\"background-color: lightsteelblue;\">\n");
      out.write("              <div class=\"row\">\n");
      out.write("                <div class=\"col-md-3 p-1\" style=\" border-radius: 10px;\"><i style=\"background-color: white; padding: 8px 15px; border-radius: 15px; font-size: 15px;  cursor: pointer;\" class=\"fa-regular fa-comment \" >12</i></div>\n");
      out.write("                <div class=\"col-md-3 p-1 \" style=\" border-radius: 10px;\"><i style=\"background-color: white; padding: 8px 15px; border-radius: 15px; font-size: 15px; cursor: pointer;\" class=\"fa-regular fa-heart\">78</i></div>\n");
      out.write("                <div class=\"col-md-6 text-end  \" style=\" border-radius: 10px; padding-top: 4px;\"><i style=\"background-color:#6A67CE; padding: 8px 15px; border-radius: 15px; font-size: 15px; font-family:  sans-serif ;\" class=\"text-light\">More</i></div>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"col-md-4\">\n");
      out.write("          <div class=\"card\" style=\"width: 18rem;\">\n");
      out.write("            <img src=\"pics/e1.jpeg\" class=\"card-img-top\" alt=\"...\">\n");
      out.write("            <div class=\"card-body\">\n");
      out.write("              <h5 class=\"card-title\" style=\"color: #6A67CE;\">EDUCATIONAL</h5>\n");
      out.write("              <p class=\"card-text\">By an admin, Oct-2016</p>\n");
      out.write("              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>\n");
      out.write("            </div>\n");
      out.write("        \n");
      out.write("            <div class=\"card-body\" style=\"background-color: lightsteelblue;\">\n");
      out.write("              <div class=\"row\">\n");
      out.write("                <div class=\"col-md-3 p-1\" style=\" border-radius: 10px;\"><i style=\"background-color: white; padding: 8px 15px; border-radius: 15px; font-size: 15px;  cursor: pointer;\" class=\"fa-regular fa-comment \" >12</i></div>\n");
      out.write("                <div class=\"col-md-3 p-1 \" style=\" border-radius: 10px;\"><i style=\"background-color: white; padding: 8px 15px; border-radius: 15px; font-size: 15px; cursor: pointer;\" class=\"fa-regular fa-heart\">78</i></div>\n");
      out.write("                <div class=\"col-md-6 text-end  \" style=\" border-radius: 10px; padding-top: 4px;\"><i style=\"background-color:#6A67CE; padding: 8px 15px; border-radius: 15px; font-size: 15px; font-family:  sans-serif ;\" class=\"text-light\">More</i></div>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"col-md-4\">\n");
      out.write("          <div class=\"card\" style=\"width: 18rem;\">\n");
      out.write("            <img src=\"pics/e3.jpeg\" class=\"card-img-top\" alt=\"...\">\n");
      out.write("            <div class=\"card-body\">\n");
      out.write("              <h5 class=\"card-title\" style=\"color: #6A67CE;\">EDUCATIONAL</h5>\n");
      out.write("              <p class=\"card-text\">By an admin, Oct-2016</p>\n");
      out.write("              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>\n");
      out.write("            </div>\n");
      out.write("        \n");
      out.write("            <div class=\"card-body\" style=\"background-color: lightsteelblue;\">\n");
      out.write("              <div class=\"row\">\n");
      out.write("                <div class=\"col-md-3 p-1\" style=\" border-radius: 10px;\"><i style=\"background-color: white; padding: 8px 15px; border-radius: 15px; font-size: 15px; cursor: pointer;\" class=\"fa-regular fa-comment  \" >12</i></div>\n");
      out.write("                <div class=\"col-md-3 p-1\" style=\" border-radius: 10px;\"><i style=\"background-color: white; padding: 8px 15px; border-radius: 15px; font-size: 15px; cursor: pointer;\" class=\"fa-regular fa-heart\">78</i></div>\n");
      out.write("                <div class=\"col-md-6 text-end  \" style=\" border-radius: 10px; padding-top: 4px;\"><i style=\"background-color:#6A67CE; padding: 8px 15px; border-radius: 15px; font-size: 15px; font-family:  sans-serif ;\" class=\"text-light\">More</i></div>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("<!-- Contact -->\n");
      out.write("<form class=\"container-fluid  Contact\" action=\"contactProcess.jsp\" method=\"post\" id=\"contact\">\n");
      out.write("        <div class=\"h1 text-center pt-5 text-light\" >Contact Us</div>\n");
      out.write("        <div class=\"row m-5 \">\n");
      out.write("         <div class=\"col-md-12\">\n");
      out.write("          <label  class=\"form-label\">Message</label>\n");
      out.write("          <input type=\"text\"  class=\"form-control p-5\" name=\"msg\" id=\"exampleInputEmail1\" aria-describedby=\"emailHelp\">      \n");
      out.write("         </div>\n");
      out.write("         <div class=\"col-md-4\">\n");
      out.write("          <label  class=\"form-label\">Name</label>\n");
      out.write("          <input type=\"text\"  class=\"form-control \" name=\"name\" id=\"exampleInputEmail1\" aria-describedby=\"emailHelp\">      \n");
      out.write("         </div>\n");
      out.write("         <div class=\"col-md-4\">\n");
      out.write("          <label for=\"exampleInputEmail1\" class=\"form-label\">Email</label>\n");
      out.write("          <input type=\"email\"  class=\"form-control \" name=\"email\" id=\"exampleInputEmail1\" aria-describedby=\"emailHelp\">      \n");
      out.write("         </div>\n");
      out.write("         <div class=\"col-md-4\">\n");
      out.write("          <label for=\"exampleInputEmail1\" class=\"form-label\">Contact</label>\n");
      out.write("          <input type=\"number\"  class=\"form-control \" name=\"cnt\" id=\"exampleInputEmail1\" aria-describedby=\"emailHelp\">       \n");
      out.write("         </div>\n");
      out.write("         <div class=\"col-md-2 p-5\">\n");
      out.write("            <button type=\"submit\" class=\"btn btn-outline-light  \">Submit</button>\n");
      out.write("         </div>\n");
      out.write("        </div>\n");
      out.write("</form>\n");
      out.write("\n");
      out.write("<!-- Footer  -->\n");
      out.write("<div class=\"container-fluid p-5 Footer\" >\n");
      out.write("  <div class=\"row p-5\">\n");
      out.write("    <div class=\"col-md-4\">\n");
      out.write("        <div class=\"h3\">ABOUT US</div>\n");
      out.write("      <div class=\"h6\">\n");
      out.write("        Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.\n");
      out.write("        <br>\n");
      out.write("        Excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum.\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"col-md-4\">\n");
      out.write("      <div class=\"h3\"> OPTIONS</div>\n");
      out.write("            <a href=\"#home\" style=\" text-decoration: none;\">HOME</a> <br>\n");
      out.write("            <a href=\"#about\" style=\" text-decoration: none;\">ABOUT US</a> <br>\n");
      out.write("            <a href=\"#service\" style=\" text-decoration: none;\">SERVICES</a> <br>\n");
      out.write("            <a href=\"#events\" style=\" text-decoration: none;\">EVENTS</a> <br>\n");
      out.write("            <a href=\"#contact\" style=\" text-decoration: none;\">CONTACT</a> \n");
      out.write("          </ul>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"col-md-4\">\n");
      out.write("      <div class=\"h3\">ADDRESS</div>\n");
      out.write("      <p> 738 Diamond Road, New York City</p>\n");
      out.write("      <p>info@example.com</p>\n");
      out.write("      <p>(0123) 0111 111 222</p>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("  <div class=\"h6 pt-1 \" style=\"border-top: 1px solid gray; color: #6A67CE;\">Copyright @2023 All rights reserved [This template is made by Mr.Shahid-Nadaf</div>\n");
      out.write("</div>\n");
      out.write("    </div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
